name: Green
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78a3b6'
    - '#f3f4ee'
    - '#d0cbad'
    - '#71705c'
    - '#1e2629'
  brandStrength: 1
  lightness: 0.23819086723960936
  saturation: 0.6843251502141356
  rhythmicContrast: 0.25
purpose: []
