name: Green
favicon: null
layout_spectrum: 0.63803
typography_spectrum: 0.32578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78a3b6'
    - '#f3f4ee'
    - '#d0cbad'
    - '#71705c'
    - '#1e2629'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
