name: Green
favicon: null
layout_spectrum: 0.94898
typography_spectrum: 0.60291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8750239044893533
  lightness: 0.23819086723960936
  saturation: 0.6843251502141356
  rhythmicContrast: 0.4797327104024589
purpose: []
